### ISSUE TITLE
The release OpenCvSharp 4.10 is ready

### ISSUE THREAD

**Issue by aropb** [sdcb/OpenVINO.NET#16]
Hi,

We expect very much Sdcb.OpenCvSharp4.mini.runtime's new version.
Thanks.

**Comment by sdcb** [comment]
I'll upgrade when I available, thanks for your attending

**Comment by aropb** [comment]
Thank you, we are waiting for you

**Comment by aropb** [comment]
> I'll upgrade when I available, thanks for your attention

Thank you for your job!

We are waiting for the update of Sdcb.OpenCvSharp4.mini.runtime.*

It is important for us:
Sdcb.OpenCvSharp4.mini.runtime.centos.7-x64

Thanks.

**Comment by aropb** [comment]
Hello,

Still waiting Sdcb.OpenCvSharp4.mini.runtime.*
Thanks.

**Comment by sdcb** [comment]
You don't need latest version to run

**Comment by aropb** [comment]
Hi,

It is possible, but then such errors may occur:
https://github.com/sdcb/opencvsharp-mini-runtime/issues/2

API and runtime library versions must be consistent.
It is impossible to know exactly where the error will be.

Then why update the API but not update the runtime?

Thank you.

**Comment by sdcb** [comment]
Sorry my mini runtime does not compile FFmpeg(which only compiled core, imgproc, imgcodec), it's not caused by 4.9 issue

**Comment by aropb** [comment]
Shouldn't you expect version 4.9 of the runtime?

**Comment by sdcb** [comment]
According to your error: `Error using VideoWriter: Unable to find an entry point named 'videoio_VideoWriter_fourcc' in shared library 'OpenCvSharpExtern'.`

it seems missing ffmpeg module or videoio module, which is not compiled in the mini version.

**Comment by aropb** [comment]
It's not my fault. I'm just waiting for the current version 4.9 of the runtime mini.

**Comment by aropb** [comment]
OpenCvSharp4 is available 4.10.0.20240616

**Comment by aropb** [comment]
And why is it closed?
Now is OpenCvSharp4 mini runtime version 4.8
