### ISSUE TITLE
Sdcb.OpenVINO.Extensions.OpenCvSharp4的 0.6.1 版本 参数顺序写错了吗？

### ISSUE THREAD

**Issue by mzmlld** [sdcb/OpenVINO.NET#20]
Sdcb.OpenVINO.Extensions.OpenCvSharp4

public static unsafe Tensor AsTensor(this Mat mat)
    {
        if (mat == null) throw new ArgumentNullException(nameof(mat));

        return new Tensor(new MatTensorBuffer(mat), new NCHW(1, mat.Height, mat.Width, mat.Type().Channels));
    }
的new NCHW(1, mat.Height, mat.Width, mat.Type().Channels)  

转到Sdcb.OpenVINO  0.6.2版和0.6.1版 看到顺序不一致
public NCHW(int NumberOfBatches, int Channels, int Height, int Width)
        {
            this.NumberOfBatches = NumberOfBatches;
            this.Channels = Channels;
            this.Height = Height;
            this.Width = Width;
        }

**Comment by sdcb** [comment]
这个我仔细看了一下，其实唯一的问题是可能不应该用NCHW这个类，用Shape这个类更贴切，我会修改一下——但实际上结果是没有任何区别的。

**Comment by theonewolf** [comment]
@sdcb can you release a new package with this fix?  I hit it today!
