### ISSUE TITLE
Using only the Sdcb.OpenVINO.PaddleOCR without Sdcb.OpenVINO

### ISSUE THREAD

**Issue by aropb** [sdcb/OpenVINO.NET#21]
Hi,

It's not critical. 
But previously I only used package Sdcb.OpenVINO.PaddleOCR.

If you change only the Sdcb.OpenVINO, without changing dependencies in the Sdcb.OpenVINO.PaddleOCR, then now it doesn't work that way. 

We have to add Sdcb.OpenVINO to the project. 
It just needs clarity on how to do it right?

Thanks.

**Comment by sdcb** [comment]
Yes you needs to install both Sdcb.OpenVINO.PaddleOCR and Sdcb.OpenVINO if you wants most recent version.
