### ISSUE TITLE
OVCore.ReadModel出错

### ISSUE THREAD

**Issue by Je88e** [sdcb/OpenVINO.NET#25]
你好，
1. 将ovcore加载表格检测模型的代码放在加载OCR模型代码的前面执行，表格检测模型可以加载成功，tableResult 是可以执行得到结果的，这时候在其下方加载OCR模型，控制台程序会直接崩溃，catch也没有获取到错误。
2. 单独加载OCR模型（去掉使用ovcore加载表格检测模型的代码）也是不会出错并且可以执行得到结果的
3. 在PaddleOCRSharp中，参考Example是同时使用这两个模型rebuildtable获取结果，在此处应该也是一样的。所以我想知道openvino.net如何同时加载两个compiledmodel
4. 麻烦您看看我的代码，运行在.net 8的控制台程序，这是一个测试程序

```csharp
public static void TableRecognize(string imgpath)
{
    try
    {
        using Mat mat = Cv2.ImRead(imgpath);

        var fullOcrModel = OnlineFullModels.ChineseV4.DownloadAsync().Result;

        using PaddleOcrAll all = new(fullOcrModel)
        {
            AllowRotateDetection = true,
            Enable180Classification = true,
        };

        all.Detector.UnclipRatio = 1.2f;
        var ocrResult = all.Run(mat);
        Console.WriteLine(ocrResult.Text);

        using var core = new OVCore();
        //这个xml和bin是我使用paddle2onnx转换为onnx模型，再通过openvino的cli转换出的表格检测模型
        var model = core.ReadModel(modelPath: @"C:\Users\Sino\AppData\Roaming\paddleocr-models\openvino_model\ppstructure_mobile_v2.0_SLANet.xml",
            binPath: @"C:\Users\Sino\AppData\Roaming\paddleocr-models\openvino_model\ppstructure_mobile_v2.0_SLANet.bin");

        //执行到该处出错
        var compiled_model = core.CompileModel(model);

        TableRecognitionModel tableModel = OnlineTableRecognitionModel.ChineseMobileV2_SLANET.DownloadAsync().Result;

        //我复制了PaddleOcrTableRecognizer 这个类，将 _compiledModel 字段作为构造函数参数传入
        using PaddleOcrTableRecognizer tableRec = new(tableModel, compiled_model);

        var tableResult = tableRec.Run(mat);
        
        string html = tableResult.RebuildTable(ocrResult);

        Console.WriteLine(html); 
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
        throw ex;
    } 
}
```

**Comment by sdcb** [comment]
core.CompileModel报错可以看看异常信息，一般是不支持动态输入，需要Reshape一下

**Comment by Je88e** [comment]
> core.CompileModel报错可以看看异常信息，一般是不支持动态输入，需要Reshape一下

1. 此处没有报出错误控制台就崩溃了
2. 我已使用openvino的cli固定了输入形状
```bash
mo --input_model ppstructure_mobile_v2.0_SLANet.onnx \
   --input_shape [1,3,488,488] \
   --output_dir openvino_model
```

**Comment by sdcb** [comment]
model.ReshapePrimaryInput(new PartialShape(1, 3, 488, 488));
加载之前reshape一下应该就可以了，但后面可能还会报其它的错

**Comment by Je88e** [comment]
> model.ReshapePrimaryInput(new PartialShape(1, 3, 488, 488)); 加载之前reshape一下应该就可以过了，但后面可能还会报其它的错

好的，我尝试一下。同时附件是onnx模型以及openvino转换的模型
[Uploading paddleocr-models.zip…]()

**Comment by sdcb** [comment]
你的模型上传似乎失败了

**Comment by Je88e** [comment]
> 你的模型上传似乎失败了

已经重新上传，谢谢

**Comment by sdcb** [comment]
发现你的模型竟然过了推理步骤，但在最后的后处理步骤时报错了

**Comment by Je88e** [comment]
> 发现你的模型竟然过了推理步骤，但在最后的后处理步骤时报错了

后处理步骤是否是CreateCompiledModel中的AfterCompiledModel(m, cm)。我好像无法看到这里的错误，因为一到这里就崩溃了

**Comment by sdcb** [comment]
重新检查了一下，是我的dict弄错了，其实发现你的模型可以一切顺利地进行推理

**Comment by Je88e** [comment]
我目前在代码中加入了
model.ReshapePrimaryInput(new PartialShape(1, 3, 488, 488));
但是依旧是控制台崩溃。

**Comment by sdcb** [comment]
你转换之后的模型，运行蛮好的，效果：
![image](https://github.com/sdcb/OpenVINO.NET/assets/1317141/ea427450-ff1f-42ca-b7b3-10af860919a3)

但你的onnx文件哪里搞到的？

**Comment by sdcb** [comment]
OVCore在我的示例中是用的OVCore.Shared，是静态共享的，但你是new出来的，按道理都可以，不知道是不是跟这个有关？

**Comment by Je88e** [comment]
请参考这个：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/paddle2onnx/readme.md
以及通过ChatGpt调查的方法，如下所示：
要使用OpenVINO将表格识别模型`ppstructure_mobile_v2.0_SLANet`进行转换，并固定模型的输入形状为 `[1, 3, 488, 488]`，你可以按照以下步骤操作：

1. **准备环境：**
   确保你已经安装了OpenVINO和相关依赖项。如果没有安装，可以参考OpenVINO的官方安装文档进行安装。

2. **下载模型：**
   确保你已经下载了`ppstructure_mobile_v2.0_SLANet`模型。假设你已经有了PaddlePaddle模型文件（`.pdmodel` 和 `.pdiparams`）。

3. **安装PaddlePaddle和Paddle2ONNX：**
   首先需要将PaddlePaddle模型转换为ONNX格式。
   ```bash
   pip install paddlepaddle paddle2onnx
   ```

4. **转换PaddlePaddle模型到ONNX：**
   使用`paddle2onnx`将PaddlePaddle模型转换为ONNX格式。
   ```bash
   paddle2onnx --model_dir /path/to/ppstructure_mobile_v2.0_SLANet \
               --model_filename inference.pdmodel \
               --params_filename inference.pdiparams \
               --save_file ppstructure_mobile_v2.0_SLANet.onnx \
               --opset_version 11
   ```

5. **安装OpenVINO：**
   如果还没有安装OpenVINO，可以通过以下命令安装。
   ```bash
   pip install openvino openvino-dev
   ```

6. **转换ONNX模型到OpenVINO IR格式：**
   使用OpenVINO的Model Optimizer工具将ONNX模型转换为IR格式。
   ```bash
   mo --input_model ppstructure_mobile_v2.0_SLANet.onnx \
      --input_shape [1,3,488,488] \
      --output_dir openvino_model
   ```

   这里的`--input_shape [1,3,488,488]`参数用于固定输入形状。

7. **加载并运行模型：**
   使用OpenVINO Runtime加载和运行转换后的模型。
   ```python
   from openvino.runtime import Core

   core = Core()
   model = core.read_model(model="openvino_model/ppstructure_mobile_v2.0_SLANet.xml")
   compiled_model = core.compile_model(model, "CPU")

   # 读取输入层和输出层
   input_layer = compiled_model.input(0)
   output_layer = compiled_model.output(0)

   # 准备输入数据
   import numpy as np
   input_data = np.random.randn(1, 3, 488, 488).astype(np.float32)

   # 推理
   result = compiled_model([input_data])[output_layer]
   print(result)
   ```

通过以上步骤，你将能够将`ppstructure_mobile_v2.0_SLANet`模型转换为OpenVINO格式，并固定其输入形状为 `[1, 3, 488, 488]`。注意在实际应用中需要使用实际的数据进行推理，而不是随机生成的数据。

**Comment by Je88e** [comment]
> OVCore在我的示例中是用的OVCore.Shared，是静态共享的，但你是new出来的，按道理都可以，不知道是不是跟这个有关？

它进入了这里，CppPtrObject的 DangerousGetHandle()
![image](https://github.com/sdcb/OpenVINO.NET/assets/51738837/a25e8b00-0394-4a83-85b9-2a73f8d50b3b)。

我尝试用用OVCore.Shared来试试

**Comment by Je88e** [comment]
> 你转换之后的模型，运行蛮好的，效果： ![image](https://private-user-images.githubusercontent.com/1317141/336360119-ea427450-ff1f-42ca-b7b3-10af860919a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODg2MzEsIm5iZiI6MTcxNzQ4ODMzMSwicGF0aCI6Ii8xMzE3MTQxLzMzNjM2MDExOS1lYTQyNzQ1MC1mZjFmLTQyY2EtYjdiMy0xMGFmODYwOTE5YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMDgwNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDczZTFkM2YzOWM4MDY2MzE2NDhkNzA4ZjEzNGExMTA2NjllMmIwNTgwMmNlMWY3OWIzYWJlNDEzMTdlYzMyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cq17nJcqT_ZesvMmzYLUTcsvPS9qjfrVietu62qdVO8)
> 
> 但你的onnx文件哪里搞到的？

我觉得我参考您的写法应该就可以了，不需要去new OVCore()，谢谢

**Comment by Je88e** [comment]
我将core改为 core = OVCore.Shared; 后，成功执行下去了，谢谢您的指导，最终可运行的代码如下：
```csharp
public static void TableRecognize()
{
    try
    {
        using Mat mat = Cv2.ImRead(@"D:\Work\仙乐\Files\供应商COA-to马总\供应商COA-to马总\100000005.jpg");

        var fullOcrModel = OnlineFullModels.ChineseV4.DownloadAsync().Result;

        using PaddleOcrAll all = new(fullOcrModel)
        {
            AllowRotateDetection = true,
            Enable180Classification = true,
        };

        all.Detector.UnclipRatio = 1.2f;
        var ocrResult = all.Run(mat);
        Console.WriteLine(ocrResult.Text);

        var core = OVCore.Shared;
        var model = core.ReadModel(modelPath: @"C:\Users\Sino\AppData\Roaming\paddleocr-models\openvino_model\ppstructure_mobile_v2.0_SLANet.xml",
            binPath: @"C:\Users\Sino\AppData\Roaming\paddleocr-models\openvino_model\ppstructure_mobile_v2.0_SLANet.bin");

        model.ReshapePrimaryInput(new PartialShape(1, 3, 488, 488));

        var compiled_model = core.CompileModel(model);

        TableRecognitionModel tableModel = OnlineTableRecognitionModel.ChineseMobileV2_SLANET.DownloadAsync().Result;

        using PaddleOcrTableRecognizer tableRec = new(tableModel, compiled_model);

        var tableResult = tableRec.Run(mat); 
        
        string html = tableResult.RebuildTable(ocrResult);

        Console.WriteLine(html); 
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message); 
    } 
}
```

**Comment by Je88e** [comment]
那么我关闭这个issue了，再次感谢您💖
