### ISSUE TITLE
Incompatibility with OpenCvSharp4.Extensions

### ISSUE THREAD

**Issue by KomodoCrypto** [sdcb/OpenVINO.NET#27]
Hello, 

After testing and isolating the problem, I found that if the any project in the solution contains the dependency package opencvsharp4.extensions, the library doesn't work and throw this error:

`System.MethodAccessException: 'Attempt by method 'Sdcb.OpenVINO.PaddleOCR.PaddleOcrDetector.Normalize(OpenCvSharp.Mat)' to access method 'OpenCvSharp.Mat..ctor(Int32, Int32, OpenCvSharp.MatType, System.Array, Int64)' failed.'
`

I tried to encapsulate it on a separate project as dll but, if the project that depends on the dll has this package, it crashes. In my case, i need that package. How to solve it or deal with that incompatibility? Thank you

**Comment by sdcb** [comment]
Hi I upgraded into most recent 4.10, can you try with latest version?
