### ISSUE TITLE
Load Model from file

### ISSUE THREAD

**Issue by KomodoCrypto** [sdcb/OpenVINO.NET#31]
Hello, 

The following method downloads the corresponding model into the default models directory,

`ocrModel = await OnlineFullModels.EnglishV4.DownloadAsync(); `

But, how to upload a model from file (that was previously downloaded), instead of downloading it?

FullOcrModel.FromDirectory() seems deprecated. Thank you

**Comment by sdcb** [comment]
instead of `FullOcrModel.FromDirectory`, you can use new `FullOcrModel(DecModel.FromDirectory, ClsModel.FromDirectory, RecModel.FromDirectory)`

**Comment by KomodoCrypto** [comment]
I am providing the paths to directories of Detection and Recognition "en_PP-OCRv3_det" and "en_PP-OCRv3_rec". However, for recognition, an argument of "labelPath" is required. Which path should I provide? Thank you
FullOcrModel ocrModel = new FullOcrModel(DetectionModel.FromDirectory(dirPathDet, ModelVersion.V3), RecognizationModel.FromDirectory(dirPathRec, null, ModelVersion.V3));
