### ISSUE TITLE
support openvino 2024.5.0

### ISSUE THREAD

**Issue by taotaow** [sdcb/OpenVINO.NET#32]
openvino 2024.5.0 is out,can you support it?thank you

**Comment by sdcb** [comment]
supported.

**Comment by taotaow** [comment]
can't find Sdcb.OpenVINO.runtime.win-x64 2024.5.0

**Comment by sdcb** [comment]
forget to upload and just uploaded: https://www.nuget.org/packages/Sdcb.OpenVINO.runtime.win-x64/2024.5.0
please try it a few minute later.
