### ISSUE TITLE
能否像PaddleSharp一样，提供OCR的Full local v3/v4 models。

### ISSUE THREAD

**Issue by p3p3pp3** [sdcb/OpenVINO.NET#4]
如题，非常感谢您的项目！

**Comment by sdcb** [comment]
PaddleSharp的本地模型我认为不是一个很好的设计，太大了点。
你现在可以先将模型下载到本地文件夹，然后用DetectionModel.FromDirectory/RecognitionModel.FromDirectory/ClassificationModel.FromDirectory去指定运行。

**Comment by p3p3pp3** [comment]
好的，谢谢。
